GET http://localhost:8080/api/v1/beer?page=0&size=10
Accept: application/json

###
GET http://localhost:8080/api/v1/beer/57ff64b2-6aab-4fd4-ba69-180acd164cfd
Accept: application/json

###
POST http://localhost:8080/api/v1/beer
Content-Type: application/json

{
  "beerName": "This The Beer Name",
  "beerStyle": "Some Style",
  "upc": 7873521025,
  "price": 123,
  "quantityOnHand": 50
}

###
PUT http://localhost:8080/api/v1/beer/57ff64b2-6aab-4fd4-ba69-180acd164cfd
Content-Type: application/json

{
  "beerName": "This The Beer Name updated",
  "beerStyle": "Some Style Updated",
  "upc": 7873521025,
  "price": 436
}

###
DELETE http://localhost:8080/api/v1/beer/57ff64b2-6aab-4fd4-ba69-180acd164cfd