GET http://localhost:8080/api/v1/beer?page=0&size=10
Accept: application/json

###
GET http://localhost:8080/api/v1/beer/4f4dd4e9-0a14-4934-8ebb-03b7a97977c6
Accept: application/json

###
POST http://localhost:8080/api/v1/beer
Content-Type: application/json

{
  "beerName": "This The Beer Name",
  "beerStyle": "Some Style",
  "upc": 1232132134
}

###
PUT http://localhost:8080/api/v1/beer/4f4dd4e9-0a14-4934-8ebb-03b7a97977c6
Content-Type: application/json

{
  "beerName": "This The Beer Name updated",
  "beerStyle": "Some Style Updated",
  "upc": 43663434349
}

###
DELETE http://localhost:8080/api/v1/beer/4f4dd4e9-0a14-4934-8ebb-03b7a97977c6